blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    
    path('', views.all_blogs,name='all_blogs'),
    path('<int:blog_id>/', views.detail, name='detail'),
]

personalweb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home,name='home'),
    path('blog/', include('blog.urls')),
]


urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.
class Blogs(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(max_length= 1000)
    #time = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models

# Create your models here.
# database creation

class Project(models.Model):
    title = models.CharField(max_length=100)
    descrtiption = models.CharField(max_length=100)
    image = models.ImageField(upload_to ='portfolio/images')
    url = models.URLField(blank= True)


    def __str__(self):
        return self.title

blog/views.py
from django.http.response import HttpResponse
from django.shortcuts import get_object_or_404, render
from .models import Blogs

# Create your views here.
def all_blogs(request):
    blogs = Blogs.objects.all()
    return render(request, 'blog.html',{'blogs':blogs}) 

def detail(request, blog_id):
    blog = get_object_or_404(Blogs, pk=blog_id)
    return render(request,'detail.html', {'blog':blog})

portfolio/views.py
from django.shortcuts import render
from .models import Project

# Create your views here.
def home(request):
    projects = Project.objects.all()
    return render(request, 'port.html', {'projects':projects}) 

blog/templates/blog.html
{% extends 'base.html' %}

{% block content %}
<h1> My blog page</h1>

{% for blog in blogs %}

   <a href="{% url 'blog:detail' blog.id %}"><h3>{{ blog.title }}</h3></a>
   <p>{{ blog.time }}</p>
   <p>{{ blog.description| truncatechars:100}}</p>
   <br>

{% endfor %}

{% endblock %}

blog/templates/detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ blog.title }}</h1>
    <p>{{ blog.description }}</p>

    {% endblock %}

portfolio/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'home' %}">Yibeltal</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a  class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:all_blogs' %}" >Blog</a>
              </li>
              <li class="nav-item">
                <a  class="nav-link" href="#">Resume</a>
              </li>
              <!-- <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li> -->
              <!-- <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
              </li>
            </ul>
            <form class="d-flex">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form> -->
          </div>
        </div>
      </nav>


      {% block content %}{% endblock %}
</body>
</html>

portfolio/templates/port.html
{% extends 'base.html' %}

{% block content %}
<h1>Landing page</h1>

    {% load static %}

    <a href="{% url 'blog:all_blogs' %}">Blog</a>
   <br>
   <a href="{% static 'port/resume.pdf' %}">Resume</a>
   <br>
   <div class="row justify-content-center my-3">
    <div class="col-5">
        <img src="{% static 'port/image0.jpeg' %}" height = 20 class="img-fluid">

    </div>

   </div>
    
    {% for project in projects %}

    <h1> {{ project.title }} </h1>
    <h3>{{ project.description }}</h3>
    <img src ="{{ project.image.url }}" height=300, width=300>
    <br>

    {% if project.url %}
    <a href= "{{ project.url }}"> LINK</a>
    {% endif %}

    {% endfor %}

{% endblock %}